### ISSUE TITLE
Make a list of endpoints

### ISSUE THREAD

**Issue by Nircek** [Pikne-Programy/pikne-zadania#1]
# see [the Wiki](https://github.com/Pikne-Programy/pikne-zadania/wiki/API)

**Comment by Nircek** [comment]
It should be public so, I will rewrite it and make a `endpoints.md` file with detailed information.

**Comment by Nircek** [comment]
## Endpoints

### `GET /api/public`
| Method | URL | Description |
| - | - | - |
| GET | `/api/public` | get all Exercises |

**Request**:
```json
```

**Response**:
```json
{
  "pociągi-dwa": "Pociągi dwa 2"
}
```
**note**: consider [#17](https://github.com/Pikne-Programy/pikne-zadania/issues/17)
**note**: shouldn't we have the exercise's type there?

***

### `GET /api/public/:id`
| Method | URL | Description |
| - | - | - |
| GET | `/api/public/:id` | get one Exercise |

**Request**:
```json
```

**Response**:
```json
{
  "type": "EqEx",
  "name": "Pociągi dwa 2",
  "content": {
    "main": "Z miast A i B odległych o \\(d=300\\mathrm{km}\\) wyruszają jednocześnie dwa pociągi z prędkościami \\(v_a=50\\mathrm{\\frac{m}{s}}\\) oraz \\(v_b=67\\mathrm{\\frac{m}{s}}\\).\nW jakiej odległości \\(x\\) od miasta A spotkają się te pociągi? Po jakim czasie \\(t\\) się to stanie?",
    "imgs": ["1.png", "2.png"],
    "unknowns": [["x", "km"], ["t", "s"]]
  }
}
```
**note**: content is ExT-dependent, shown above is the EqEx one
**note**: shouldn't unknowns be formatted in LaTeX like in `.contant.main`?

***

### `POST /api/public/:id`
| Method | URL | Description |
| - | - | - |
| POST | `/api/public/:id` | check answers |

**Request**:
```json
{
  "x": 15.000000000000004,
  "t": 13
}
```

**Response**:
```json
{
  "success": false
}
```
**note**: consider [#14](https://github.com/Pikne-Programy/pikne-zadania/issues/14)

**Comment by Marwyk2003** [comment]
I will be parsing units of the unknowns to latex and sending them to the client, so they can be simply pasted in the right place.

**Comment by MichalTheProgrammer** [comment]
If we get an error in function check() | list() | render(), we should also return
```
ctx.response.body = {
        msg: error.toString(),
      };
```

**Comment by Nircek** [comment]
In my opinion, the issue can be closed because I exported the list of endpoints to the Wiki. Feel free to reopen it if you have a reason to.

**Comment by miloszwasacz** [comment]
I noticed that unknowns of a fetched EqEx should contain "=", because they are written in LaTeX.

e.g. ```"unknowns": [["\\(x =\\)", "\\(\\mathrm{km}\\)"], ["\\(t =\\)", "\\(\\mathrm{s}\\)"]]```

**Comment by Nircek** [comment]
Oh. I think it's a mess doing it in that way. What we will do if someone wants to make an implementation which asks like `What's the value of \(x [\mathrm{km}]\)?` No, it will be better not to send unknows in LaTeX form than sending them in your way.

**Comment by miloszwasacz** [comment]
Omitting ```\(\)``` seams like a good solution.

**Comment by Nircek** [comment]
I updated the API, see https://github.com/Pikne-Programy/pikne-zadania/issues/17#issuecomment-766157678.
