### ISSUE TITLE
Session manager

### ISSUE THREAD

**Issue by Nircek** [Pikne-Programy/pikne-zadania#16]
We must somehow store in cookies a session id of a user. Currently, we don't need to have it on the server-side because the session id is only necessary as the RNG seed in the EqEx parser (#4). But it will be nice in the future to use it as an authenticator when we have user accounts. So are we making only `Math.random/UUIDv4/crypto.getRandomValues`? Or do we connect it with for example [JWT](https://deno.land/x/djwt) in v0.1? It gives us completely nothing for now. With the JWT the user will not know their RNG seed, but should it be secret? They will know the random-generated content of exercises, so the seed is completely useless for users. And if two users want to have the same variables, they can easily copy a JWT token. And the JWT token itself is not suitable for use in the RNG. We will need to encrypt in JWT's payload a user's seed if we want to access it in the RNG algorithm.

/ping @MichalTheProgrammer

**Comment by MichalTheProgrammer** [comment]
So referring to @Nircek, we do not need JWT for now. We can use cookies instead.

**Comment by Nircek** [comment]
We will store the seed in the cookies, so in the first prototype, the session manager is not necessary.

**Comment by Nircek** [comment]
Okay, we are making the second prototype now, so we also need to make the session manager and connect it to the login system (#22).

**Comment by Nircek** [comment]
We will have all JWTs stored in the database to make logging out possible. There can be a repetitive job cleaning up all expired tokens. We can make that like in #31.

**Comment by Nircek** [comment]
Sessions works! :tada:

(with small bugs but it works)
