### ISSUE TITLE
Order of exercises

### ISSUE THREAD

**Issue by Nircek** [Pikne-Programy/pikne-zadania#17]
Do we want to preserve the order of exercises? In my view, it can be useful to have a property like `priority` to determine which should be first.
We all know that in [pikne-zadania-exercises](https://github.com/Pikne-Programy/pikne-zadania-exercises) repo we will copy the exercises from [astrofiz.pl](http://astrofiz.pl/) (with the agreement of the owner :heart:) and there are sections and subsections in a logical order. We can decide to make a list of priorities, for example:
```
1x - mechanika
  10 - kinematyka
  11 - dynamika
  12 - rzuty
  13 - pęd
  14 - tarcie
  ...
2x - grawitacja
...
```
I know it's a mess. Eventually, we can make a list of tags with assigned priorities. If there is more than one tag assigned, we list exercises considering the most important one.

@miloszwasacz what do you think from the frontend side?

**Comment by MichalTheProgrammer** [comment]
This solution has some drawbacks. In one field there might be more than ten chapters, so we shall use 3-digit priorities and this can be misleading. However I think this is a good idea, maybe we can consider using alphanumeric notation.

**Comment by Nircek** [comment]
@MichalTheProgrammer what about this solution?
> Eventually, we can make a list of tags with assigned priorities. If there is more than one tag assigned, we list exercises considering the most important one.

Making the priorities in 2- or 3-digit format has one big drawback. If we want to add one subsection, we shift all the digits of the whole section. For example, consider adding a subsection between "10 - kinematyka" and "11 - dynamika". The new one will have a priority "11" thus we have to shift priorities "11", "12"...

**Comment by Nircek** [comment]
In my view, the separate file for the order of tags (there didn't have to be priorities at all) is better. There can be even a text file with listed sections and subsections like:
```
mechanika/kinematyka
mechanika/dynamika
mechanika/rzuty
...
mechanika
grawitacja/prawo-ciążenia
...
grawitacja
...
```
```

**Comment by Nircek** [comment]
We agreed that we make the folder structure of sections and subsections.
So there will be files like `mechanika/kinematyka/01pociągi-dwa.txt`.
And I will change the API in #1, next the issue can be closed.

**Comment by Nircek** [comment]
Okay, according to https://github.com/Pikne-Programy/pikne-zadania/issues/17#issuecomment-758762211, we can do a list of excercises (say `/index.yaml`) and its order like:
```yaml
 - kinematyka:
    - mechanika:
       - pociagi-dwa
       - czerpak
       - [ ... ]
    - dynamika:
       - [ ... ]
    - [ ... ]
 - grawitacja:
    - [ ... ]
 - [ ... ]
```
@MichalTheProgrammer you can make this handling.

**Comment by Nircek** [comment]
We decided to store all exercises in one folder. But in my opinion, we should split them into subjects. So there will be folders named after them. And in one folder, all exercises with `.txt` extension and `index.yml` file with the exercises' hierarchy. But we should consider that the file names can also occur in other subjects, then ids are not unique. I will add the subject name to the GET (and POST) request of each one.

**Comment by Nircek** [comment]
So it's resolved, we will implement this in the future. Reopen if you need to.
