### ISSUE TITLE
Handling Errors

### ISSUE THREAD

**Issue by Marwyk2003** [Pikne-Programy/pikne-zadania#18]
We need to create some custom error types the Excercise class can throw.

**Comment by Nircek** [comment]
The errors can occur in any Exercise (like parse error) or in Controller itself (like not found or unknown ExT). All of that should throw exceptions in a simmiliar way. And we should send an error message to a user with an appropriate HTTP status code.

**Comment by MichalTheProgrammer** [comment]
@Marwyk2003 
In 3c6494b45d9c5ca618e5c492e25332db3b0ec326, we're using ```throw new Error()``` to handle errors. Currently, it is enough. But we shouldn't close this issue, because there might be some new errors in the future. Below an example of this syntax.
https://github.com/Pikne-Programy/pikne-zadania/blob/3c6494b45d9c5ca618e5c492e25332db3b0ec326/controllers/exercisesController.ts#L45

**Comment by Nircek** [comment]
There is no exercise specified in an error thrown in `render()` or `check()` functions. For example:
```
this.variables[name].rand is not a function TypeError: this.variables[name].rand is not a function
    at EquationExercise.render (equationExercise.ts:331:53)
    at exercisesController.ts:162:36
    at Function.exists (exercisesController.ts:143:13)
    at exercisesController.ts:158:35
    at Function.predictDeath (exercisesController.ts:128:13)
    at ExercisesController.get (exercisesController.ts:156:31)
    at dispatch (middleware.ts:41:13)
    at seed (seedMiddleware.ts:14:9)
    at dispatch (middleware.ts:41:13)
    at router.ts:866:20
```

**Comment by MichalTheProgrammer** [comment]
I don't think we need it in the first prototype. Moving it to the second milestone.

**Comment by MichalTheProgrammer** [comment]
We need to add HTTP status code support.

**Comment by Nircek** [comment]
I'd rather use [`HttpError`](https://github.com/oakserver/oak/blob/main/httpError.ts?use-commit-when-not-available=6b4d101941457530370b8a4bd4dd6dc156f08b9b) when the function has the `RouterContext` in parameters. Like here:
https://github.com/Pikne-Programy/pikne-zadania/blob/35c2385c6c24ccf50ea6c98f70d7c42b49acc084/backend/middleware/auth.ts#L9

**Comment by Nircek** [comment]
> There is no exercise specified in an error thrown in `render()` or `check()` functions.

@MichalTheProgrammer And it's still a problem.

**Comment by Nircek** [comment]
> 
> 
> > There is no exercise specified in an error thrown in `render()` or `check()` functions.
> 
> @MichalTheProgrammer And it's still a problem.

Okay, it is obsoleted now, see:
https://github.com/Pikne-Programy/pikne-zadania/blob/59224f50747c66bf9a6eb156d266716b71b8870a/backend/server.ts#L18
