### ISSUE TITLE
Dockerize the frontend and add DB

### ISSUE THREAD

**Issue by Nircek** [Pikne-Programy/pikne-zadania#19]
I think we should use Docker Compose and add a Mongo DB container.

**Comment by Nircek** [comment]
@miloszwasacz what do you finally want to use in the frontend? Frameworks, etc.

**Comment by miloszwasacz** [comment]
> @miloszwasacz what do you finally want to use in the frontend? Frameworks, etc.

In v0.2 I'll be moving to Angular so I'll need Angular CLI to build the app. I've found some [tutorial](https://wkrzywiec.medium.com/build-and-run-angular-application-in-a-docker-container-b65dbbc50be8), it may be useful for you @Nircek.

**Comment by Nircek** [comment]
I have seen this before but thanks. :wink:

**Comment by Nircek** [comment]
If there's a connection error, DB requests should wait for a while and retry due to possible DB upgrade. And fail if it can't succeed anyway.

**Comment by Nircek** [comment]
@miloszwasacz I'm waiting for a commit that I can use as angular frontend submodule.

@MichalTheProgrammer We should decide between Mongo and Redis.

**Comment by Nircek** [comment]
Angular build needs optimization. Links:
 - https://stackoverflow.com/questions/53995948/warning-in-budgets-maximum-exceeded-for-initial
 - https://stackoverflow.com/questions/45242553/how-to-speed-up-the-angular-build-process
 - https://stackoverflow.com/questions/61304548/simple-angular-9-project-compiles-whole-angular-material-es2015-as-esm2015
 - https://stackoverflow.com/questions/55757966/very-slow-ng-build-prod-in-docker
 - https://github.com/angular/angular-cli/issues/17017#issuecomment-609921036

**Comment by Nircek** [comment]
It was done in fd6fd61720d7247946bcf7ab67829f60397d8880. I'm closing.
