### ISSUE TITLE
Support images in EqEx

### ISSUE THREAD

**Issue by Nircek** [Pikne-Programy/pikne-zadania#23]

**Comment by Marwyk2003** [comment]
Images are stored in render's YAML type under `conent[unknowns]`.
`conent[unknowns]` is an array of strings (or an empty array if no images were provided).

**Comment by Nircek** [comment]
Images will be stored in a `static` subfolder of each subject folder. There can be any static content. It can be accessed by `/api/static/:subject/:file` endpoint (#25). We can send it in the EqEx via the `imgs` field but shouldn't it be universal for all Exercises?

**Comment by Nircek** [comment]
I added images in Pikne-Programy/pikne-zadania-exercises@3486bb34b23d691ee03e54d9e765c72cd2eafcbd

**Comment by Nircek** [comment]
@miloszwasacz review if it works, please. Feel free to reopen the issue if you have any problems.

**Comment by miloszwasacz** [comment]
There seems to be an inconsistency in the EqEx structure. According to API images are in `imgs` field, but the server sends a JSON with `img` field.

**Comment by miloszwasacz** [comment]
Everything seems fine, closing.
