### ISSUE TITLE
Store an exercise answer status

### ISSUE THREAD

**Issue by Nircek** [Pikne-Programy/pikne-zadania#24]
It depends on #22. Each student can solve an exercise from the public database, and we should store the last status (correct, wrong or empty answer). We should collect the correctness of a wrong answer (say in percents) if we close #14.

**Comment by Nircek** [comment]
We will send a `done` value with an exercise list. It will be `null` if no solution was ever sent or a number from 0 to 1 describing the correctness (see #14) of the sent answer.

**Comment by Nircek** [comment]
The statuses of logged-in users will be stored on the server. There will be a `done` field in the list of exercises (`GET /api/public`) of an authorised user. But what about not registered ones? I think it's nice to store their exercise statuses. But we don't need it on the server-side, so my idea is to preserve a list of solved exercises in the cookies (or whatever) on the client-side and never send it to the server.

@miloszwasacz is it possible?

**Comment by miloszwasacz** [comment]
> @miloszwasacz is it possible?

I will look into it.
