### ISSUE TITLE
[v0.2] Make a list of endpoints

### ISSUE THREAD

**Issue by Nircek** [Pikne-Programy/pikne-zadania#25]
see [the wiki](https://github.com/Pikne-Programy/pikne-zadania/wiki/API)

**Comment by Nircek** [comment]
We should consider #23, #14, #22, #24 an #16 in it.
And maybe #26, and maybe #20.

**Comment by Nircek** [comment]
I will rewrite it in a nice MD form soon.
There's the first draft written yesterday:
```
### GET /api/public
Request:

Response:

[
  {
    "name": "fizyka",
    "children": [
      {
        "name": "mechanika",
        "children": [
          {
            "name": "kinematyka",
            "children": [
              {
                "name": "Pociągi dwa",
                "children": "pociagi-dwa",
                "done": 34 // Number 0-100 procent poprawnosc; Null - nie zrobione
              }
            ]
          }
        ]
      }
    ]
  }
]

### GET /api/public/:subject/:id
Request:

Response:

{
  "type": "EqEx",
  "name": "Pociągi dwa 2",
  "content": {
    "main": "Z miast A i B odległych o \\(d=300\\mathrm{km}\\) wyruszają jednocześnie dwa pociągi z prędkościami \\(v_a=50\\mathrm{\\frac{m}{s}}\\) oraz \\(v_b=67\\mathrm{\\frac{m}{s}}\\).\nW jakiej odległości \\(x\\) od miasta A spotkają się te pociągi? Po jakim czasie \\(t\\) się to stanie?",
    "imgs": ["1.png", "2.png"], // /api/static/:subject/:file
    "unknowns": [["x", "\\mathrm{km}"], ["t", "\\mathrm{s}"]]
  }
}

### POST /api/public/:subject/:id
# in the order of unknowns
Request:

[15.000000000000004, 13]

Response:

[false, true]
# 400 - jak zła ilość unknowns albo dowolny błąd w strukturze JSONa
# 404 - nie ma zadania


### POST /api/register
{
  "login": "user@example.com",
  "name": "User",
  "hashed_password": "TWnFgm9zeiByb2JpIHphcsSFYmlzdHkgZnJvbnRlbmQsIHBvemRyYXdpYW0=+",
  "number": 11, // or null
  "invitation": "QwErTy58"
}
# 400 - wrong JSON structure
# 403 - wrong invitation code
# 409 - user (email) exists

### POST /api/login
{
  "login": "user@example.com", // admin
  "hashed_password": "TWnFgm9zeiByb2JpIHphcsSFYmlzdHkgZnJvbnRlbmQsIHBvemRyYXdpYW0="
}
# 400 - wrong JSON structure
# 401 - blad logowania

### GET /api/account
{
    "name":"User",
    "number": 11,
    "team": 1
}
# 400
# 403

### GET /api/teams
# all teams owned
[
  // 0 - hardcoded admin
  {
    "id": 1,
    "name": "Teachers", // from config
    "assignee": "Smith", // UID
    "open": true
  },
  {
    "id": 2,
    "name": "2d"
  },
  {
    "id": 3,
    "name": "3d"
  }
]
# 403

### POST /api/teams
# new team
{
  "name": "2d"
}

Response:
1
# 400, 403

### POST /api/teams/:id/open
# change invitation status
"QwErTy58"

### POST /api/teams/:id/close
# change invitation status

### GET /api/teams/:id
{
  "name": "2d",
  "assignee": "Smith"
  "members": [
    {
      "id": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", // hashed email
      "name": "User",
      "number": 11
    }
  ]
}
# 403 - user może wyświetlić SWÓJ team

### DELETE /api/teams/:id/:userid
# 200, 404

### POST /api/teams/:id/:userid
# new number
Response:
34

### POST /api/teams/:id
# new name
"3d"

### POST /api/root/teams/:id
# change assignee // can't change assignee of "Teachers" team
"1057a9604e04b274da5a4de0c8f4b4868d9b230989f8c8c6a28221143cc5a755"
```

**Comment by Nircek** [comment]
@Pikne-Programy/pikne-zadania should we send the list of exercises (`/api/public`) to the client that has an invalid auth token?  We send it when the user is not logged in. But what if the user tries to authenticate with an expired token? We can behave like the user is not registered, or we can send a `401 Unathorized` code stating that the credentials are wrong and they should log in again (or clear auth token).

@miloszwasacz what do you feel about all this?

**Comment by miloszwasacz** [comment]
> we can send a ```401 Unathorized``` code stating that the credentials are wrong and they should log in again (or clear auth token)

I think this would be a better option

**Comment by Nircek** [comment]
Ok, but you know that the client will have to send another `GET /api/public` request to get the list of exercises if the first one return 401?

**Comment by miloszwasacz** [comment]
That won't be a problem.

**Comment by Nircek** [comment]
The same problem occurs when we try to get the exercise or submit a solution.

@miloszwasacz What about the authorized user that was doing an exercise so long that the auth token expired? They will get a `401 Unathorized` error code if they try to submit a solution.

I think the long-lasting tokens are the best option, but at least we should consider that this can happen.

**Comment by Nircek** [comment]
I have rewritten the API into Markdown but this is still under construction. See [the wiki](https://github.com/Pikne-Programy/pikne-zadania/wiki/API).

**Comment by Nircek** [comment]
I added a static content request. See https://github.com/Pikne-Programy/pikne-zadania/issues/23#issuecomment-782935879.

**Comment by Nircek** [comment]
Do we need an endpoint for getting the current invitation code of a team? Now we have setters and no getter.

**Comment by miloszwasacz** [comment]
> Do we need an endpoint for getting the current invitation code of a team? Now we have setters and no getter.

We could add this to [`GET /api/teams/:id`](https://github.com/Pikne-Programy/pikne-zadania/wiki/API#get-apiteamsid).
