### ISSUE TITLE
Describe the EqEx specs

### ISSUE THREAD

**Issue by Nircek** [Pikne-Programy/pikne-zadania#3]
depends on #2

**Comment by Nircek** [comment]
All the EqEx issues is moved to the [pikne-zadania-exercises repo](https://github.com/Pikne-Programy/pikne-zadania-exercises). This issue will be closed when the v0.1 will be released (Pikne-Programy/pikne-zadania-exercises#1).

**Comment by Nircek** [comment]
I have decided to write the EqEx spec in the Wiki of this repo, so it's [here](https://github.com/Pikne-Programy/pikne-zadania/wiki/EqEx).

**Comment by Nircek** [comment]
There is still a lack in the documentation. We should add info about using LaTeX and be more specific in the calculation process description.

Due to that, I think we can keep this issue open and figure out how to add images in v0.2 EqEx specs. In my opinion, the best way will be adding `img` folder in each subject folder and add relative to it paths in exercise files.

**Comment by Nircek** [comment]
It should be stated that `imgs` refer to the path relative to the `/api/static/:subject/` (see https://github.com/Pikne-Programy/pikne-zadania/issues/23#issuecomment-782935879)

**Comment by Marwyk2003** [comment]
Units like `1/s` should be written as `/s` in EqEx format.
For example, T=10/s would be rendered as <img src="https://render.githubusercontent.com/render/math?math=T=10\frac{1}{\mathrm{s}}">.

**Comment by Marwyk2003** [comment]
I've finished writing the specification. You can check it out [here](https://github.com/Pikne-Programy/pikne-zadania/wiki/EqEx).
