### ISSUE TITLE
Change licence to more restricting

### ISSUE THREAD

**Issue by miloszwasacz** [Pikne-Programy/pikne-zadania#30]
We should change the licence from MIT to more resticting one (e.g. GPL)

**Comment by Nircek** [comment]
It's a good idea. What do you think @Marwyk2003, @MichalTheProgrammer?

**Comment by Nircek** [comment]
There's a list of all our files:
- [x] backend/router.ts
- [x] backend/server.ts
- [x] backend/exts/exts.ts
- [x] backend/exts/eqex/equationExercise.ts
- [x] backend/controllers/authController.ts
- [x] backend/controllers/exercisesController.ts
- [x] backend/middleware/seedMiddleware.ts
- [x] backend/run.sh
- [x] backend/types.ts
- [x] backend/Dockerfile
- [x] backend/denon.dockerfile
- [x] backend/exercise.ts
- [x] backend/deps.ts
- [x] docker-compose.latest.yml
- [x] docker-compose.yml
- [ ] frontend/package-lock.json
- [ ] frontend/src/manifest.webmanifest
- [x] frontend/src/polyfills.ts
- [x] frontend/src/ass.ts/.gitkeep
- [x] frontend/src/app/public-exercises/public-exercises.component.spec.ts
- [ ] frontend/src/app/public-exercises/public-exercises.component.scss
- [ ] frontend/src/app/public-exercises/public-exercises.component.html
- [x] frontend/src/app/public-exercises/public-exercises.component.ts
- [ ] frontend/src/app/app.component.scss
- [x] frontend/src/app/app.component.spec.ts
- [x] frontend/src/app/server-routes.ts
- [ ] frontend/src/app/subject-select/subject-select.component.html
- [ ] frontend/src/app/subject-select/subject-select.component.scss
- [x] frontend/src/app/subject-select/subject-select.component.ts
- [x] frontend/src/app/subject-select/subject-select.component.spec.ts
- [ ] frontend/src/app/content/content.component.scss
- [ ] frontend/src/app/content/content.component.html
- [x] frontend/src/app/content/content.component.spec.ts
- [x] frontend/src/app/content/content.component.ts
- [x] frontend/src/app/app.component.ts
- [ ] frontend/src/app/app.component.html
- [x] frontend/src/app/exercises/exercise.component.spec.ts
- [x] frontend/src/app/exercises/exercise.component.ts
- [x] frontend/src/app/exercises/eqex/eqex.component.ts
- [x] frontend/src/app/exercises/eqex/eqex.component.spec.ts
- [ ] frontend/src/app/exercises/eqex/eqex.component.html
- [ ] frontend/src/app/exercises/eqex/eqex.component.scss
- [ ] frontend/src/app/exercises/exercise.component.scss
- [ ] frontend/src/app/exercises/exercise.component.html
- [x] frontend/src/app/exercises/exercises.ts
- [x] frontend/src/app/app.module.ts
- [ ] frontend/src/app/account/login/login.component.scss
- [ ] frontend/src/app/account/login/login.component.html
- [x] frontend/src/app/account/login/login.component.ts
- [x] frontend/src/app/account/login/login.component.spec.ts
- [x] frontend/src/app/account/account.service.ts
- [x] frontend/src/app/account/account.service.spec.ts
- [ ] frontend/src/app/account/register/register.component.html
- [x] frontend/src/app/account/register/register.component.ts
- [x] frontend/src/app/account/register/register.component.spec.ts
- [x] frontend/src/app/app-routing.module.ts
- [x] frontend/src/app/exercise-service/exercise.service.spec.ts
- [x] frontend/src/app/exercise-service/exercise.service.ts
- [x] frontend/src/app/helper/tests/server.ts
- [x] frontend/src/app/helper/tests/tests.config.ts
- [x] frontend/src/app/helper/screen-size.service.spec.ts
- [x] frontend/src/app/helper/utils.ts
- [x] frontend/src/app/helper/screen-size.service.ts
- [ ] frontend/src/app/navigation/tabs/tab.component.scss
- [x] frontend/src/app/navigation/tabs/tab.component.ts
- [x] frontend/src/app/navigation/tabs/tab.component.spec.ts
- [ ] frontend/src/app/navigation/tabs/tab.component.html
- [x] frontend/src/app/navigation/navingation.service.spec.ts
- [x] frontend/src/app/navigation/navbar/navbar.component.spec.ts
- [ ] frontend/src/app/navigation/navbar/navbar.component.scss
- [x] frontend/src/app/navigation/navbar/navbar.component.ts
- [ ] frontend/src/app/navigation/navbar/navbar.component.html
- [x] frontend/src/app/navigation/sidenav/sidenav.directive.spec.ts
- [x] frontend/src/app/navigation/sidenav/sidenav.component.spec.ts
- [ ] frontend/src/app/navigation/sidenav/sidenav.component.html
- [ ] frontend/src/app/navigation/sidenav/sidenav.component.scss
- [x] frontend/src/app/navigation/sidenav/sidenav.directive.ts
- [x] frontend/src/app/navigation/sidenav/sidenav.component.ts
- [x] frontend/src/app/navigation/navingation.service.ts
- [x] frontend/src/test.ts
- [x] frontend/src/environments/environment.ts
- [x] frontend/src/environments/environment.prod.ts
- [ ] frontend/src/styles.variables.scss
- [ ] frontend/src/index.html
- [x] frontend/src/main.ts
- [ ] frontend/src/styles.scss
- [ ] frontend/.editorconfig
- [ ] frontend/.gitignore
- [ ] frontend/package.json
- [x] frontend/nginx.dockerfile
- [ ] frontend/.dockerignore
- [ ] frontend/karma.conf.js
- [ ] frontend/nginx.conf
- [x] frontend.tsconfig.spec.json
- [x] frontend.tsconfig.json
- [x] frontend/e2e/src/app.e2e-spec.ts
- [x] frontend/e2e/src/app.po.ts
- [x] frontend/e2e.tsconfig.json
- [ ] frontend/e2e/protractor.conf.js
- [x] frontend/Dockerfile
- [ ] frontend/ngsw-config.json
- [ ] frontend/.browserslistrc
- [x] frontend/angular.dockerfile
- [ ] frontend/angular.json
- [x] frontend.tslint.json
- [x] frontend.tsconfig.app.json
- [ ] docker-compose.prod.yml

**Comment by MichalTheProgrammer** [comment]
Agreed.

**Comment by Marwyk2003** [comment]
I agree.
