### ISSUE TITLE
API v0.3

### ISSUE THREAD

**Issue by Nircek** [Pikne-Programy/pikne-zadania#34]
# see [the available revisions](https://github.com/Pikne-Programy/pikne-zadania/issues/34#issuecomment-916038600)
- change params in the URL endpoint to JSON in HTTP request

**Comment by Nircek** [comment]
# Endpoints - v0.3 (discuss at [#34](https://github.com/Pikne-Programy/pikne-zadania/issues/34))

// define error messages
// define common statuses of requests

// ToC

## Exercise

### `/api/exercise/list`
note: private exercises (ones with `_` prefix) will be shown for authorized users with proper permissions
**note**: Elements of the root list must be subject objects. \
**note**: `done` property is stated only when the user is authorized,
it can be `null` or a number from 0 to 1, see [#24](https://github.com/Pikne-Programy/pikne-zadania/issues/24#issuecomment-782939873).

### `/api/exercise/get`
// raw file
### `/api/exercise/check`
// ExT-dependent
### `/api/exercise/update`
// raw file
### `/api/exercise/render`
// get exercise (and correct answers if privileged)
// static content at `/img/:subject/:file`
### `/api/exercise/preview`
// render a raw file in request with given seed and response like in `/api/exercise/render` (always privileged)

## Subject
### `/api/subject/create`
// name and list of authorized users (who can see and edit)
### `/api/subject/info`
// list of authorized users
### `/api/subject/permit`
// change list of authorized users

## Auth
### `/api/auth/login`
**note**: The generation of `hashed_password` is described [here](https://github.com/Pikne-Programy/pikne-zadania/issues/22#issuecomment-789536400).
### `/api/auth/register`
**note**: The generation of `hashed_password` is described [here](https://github.com/Pikne-Programy/pikne-zadania/issues/22#issuecomment-789536400). \
**note**: `number` is a number or `null` when it's not provided. \
**note**: `login` is an email address (the hard-coded users like `root` cannot be registered). \
**note**: The registration doesn't authenticate, there should be a `POST /api/login` request afterwards.

### `/api/auth/logout`

## User
### `/api/user/current`
### `/api/user/delete`
### `/api/user/update`
### `/api/user/info`
// about one user

## Team
### `/api/team/create`
// response is id
### `/api/team/delete`
### `/api/team/update`
// invCode can be null, it will be generated
// what with "teachers" room?
### `/api/team/list`
// all teams, invitation is privileged, null if closed
### `/api/team/info`
// members, assignee, name, invitation code (if privileged)

## Group
### `/api/group/create`
// response is id
### `/api/group/delete`
### `/api/group/update`
### `/api/group/list`
// only your groups
// `assignee` if root
### `/api/group/info`
// members, assignee, name, exams
### `/api/group/join`
// ???

## Exam
### `/api/exam/create`
// name, time of beginning (or null), duration, for which group
### `/api/exam/delete`
### `/api/exam/update`
### `/api/exam/exercise`
//  [{count:1, ex:["ex1", "ex2", "ex3"]},{}]
// random 1 exercise from {ex1,ex2,ex3}
// how many points
### `/api/exam/info`
{
status, time,
pool: [{count:1, ex:["ex1", "ex2", "ex3"]},{}]
exercises: [{id,name,points,avg}, {}],
users:[{id,name,solvings: [null, [0, 0]],points,percent,grade]}]
}
### `/api/exam/user`
// stats of one test of the user
### `/api/exam/join`
// websocket (ws:// or wss://)
```
a: start
a: time
a: stop
s: info - time, exercises, points  # can be send on and on when sth changes
s->a: users - if sb logged in or if relog
[''] or ['','']
ua: exercise # response is {type,id,content}
ua: static # get static file {id, content in b64}
ua: leave # block user's test
ua: submit # {id,answer}
s: end # time's up, please send back answers

**Comment by Nircek** [comment]
There is a draft above.

**Comment by MichalTheProgrammer** [comment]
# Endpoints - v0.3

If there is an error (`4xx` or `5xx` status code), the API will return either no content or the JSON object with an error message:

```json
{
  "msg": "<error message>"
}
```

The common errors status codes are:

- 400, when the request is invalid,
- 401, when the authentication has failed or is required and is not provided,
- 500, if there is a problem on the server-side.

## Table of Content

# Exercise

## `GET /api/exercise/list`

| Method | URL                  | Description       | Special status codes |
| ------ | -------------------- | ----------------- | -------------------- |
| GET    | `/api/exercise/list` | get all Exercises | -                    |

**Request**:

```json

```

**Response**:

```json
[
  {
    "name": "fizyka",
    "children": [
      {
        "name": "mechanika",
        "children": [
          {
            "name": "kinematyka",
            "children": [
              {
                "name": "Pociągi dwa",
                "children": "pociagi-dwa",
                "done": 0.34
              }
            ]
          }
        ]
      }
    ]
  }
]
```

**note**: private exercises (ones with `_` prefix) will be shown for authorized users with proper permissions. \
**note**: Elements of the root list must be subject objects. \
**note**: `done` property is stated only when the user is authorized,
it can be `null` or a number from 0 to 1, see [#24](https://github.com/Pikne-Programy/pikne-zadania/issues/24#issuecomment-782939873).

---

## `GET /api/exercise/get`

| Method | URL                 | Description      | Special status codes |
| ------ | ------------------- | ---------------- | -------------------- |
| GET    | `/api/exercise/get` | get one Exercise | 404                  |

**Request**:

```json
{
  "subject": "fizyka",
  "id": "pociagi-dwa"
}
```

**Response**:

```json
{
  "type": "EqEx",
  "name": "Pociągi dwa 2",
  "done": 0.34,
  "content": {
    "main": "Z miast \\(A\\) i \\(B\\) odległych o \\(d=300\\;\\mathrm{km}\\) wyruszają jednocześnie\ndwa pociągi z prędkościami \\(v_a= 50\\;\\mathrm{\\frac{km}{h}}\\) oraz \\(v_b=70\\;\\mathrm{\\frac{km}{h}}\\).\nW jakiej odległości \\(x\\) od miasta \\(A\\) spotkają się te pociągi?\nPo jakim czasie \\(t\\) się to stanie?",
    "img": ["1.png", "2.png"],
    "unknowns": [
      ["x", "\\mathrm{km}"],
      ["t", "\\mathrm{s}"]
    ]
  }
}
```

**note**: `content` is ExT-dependent, shown above is the EqEx one. \
**note**: The `content` can contain links to static content. It can be accessed via `GET /img/:subject/:file` request.

---

## `POST /api/exercise/update`

| Method | URL                    | Description               | Special status codes |
| ------ | ---------------------- | ------------------------- | -------------------- |
| POST   | `/api/exercise/update` | update exercise's content | 403, 404             |

**Request**:

```json
{
  "subject": "fizyka",
  "id": "pociagi-dwa",
  "content": {
    "main": "Z miast \\(C\\) i \\(D\\) odległych o \\(d=300\\;\\mathrm{km}\\) wyruszają jednocześnie\ndwa pociągi z prędkościami \\(v_a= 50\\;\\mathrm{\\frac{km}{h}}\\) oraz \\(v_b=70\\;\\mathrm{\\frac{km}{h}}\\).\nW jakiej odległości \\(x\\) od miasta \\(A\\) spotkają się te pociągi?\nPo jakim czasie \\(t\\) się to stanie?",
    "img": ["1.png", "2.png"],
    "unknowns": [
      ["x", "\\mathrm{km}"],
      ["t", "\\mathrm{s}"]
    ]
  }
}
```

**Response**:

```json

```

**note**: `content` is ExT-dependent, shown above is the EqEx one. \
**note**: Only content can be changed.

---

## `POST /api/exercise/check`

| Method | URL                   | Description   | Special status codes |
| ------ | --------------------- | ------------- | -------------------- |
| POST   | `/api/exercise/check` | check answers | 404                  |

**Request**:

```json
{
  "subject": "fizyka",
  "id": "pociagi-dwa",
  "answers": [15.000000000000004, 13]
}
```

**Response**:

```json
[false, true]
```

**note**: It's ExT-dependent, what is shown above is appropriate for the EqEx one.

---

## `GET /api/exercise/preview`

| Method | URL                     | Description         | Special status codes |
| ------ | ----------------------- | ------------------- | -------------------- |
| GET    | `/api/exercise/preview` | preview an exercise | 403, 404             |

**Request**:

```json
{
  "subject": "fizyka",
  "id": "pociagi-dwa",
  "seed": 28123719
}
```

**Response**:



```json
{
  "type": "EqEx",
  "name": "Pociągi dwa 2",
  "content": {
    "main": "Z miast \\(A\\) i \\(B\\) odległych o \\(d=300\\;\\mathrm{km}\\) wyruszają jednocześnie\ndwa pociągi z prędkościami \\(v_a= 50\\;\\mathrm{\\frac{km}{h}}\\) oraz \\(v_b=70\\;\\mathrm{\\frac{km}{h}}\\).\nW jakiej odległości \\(x\\) od miasta \\(A\\) spotkają się te pociągi?\nPo jakim czasie \\(t\\) się to stanie?",
    "img": ["1.png", "2.png"],
    "unknowns": [
      ["x", "\\mathrm{km}"],
      ["t", "\\mathrm{s}"]
    ],
    "correct": [12, 21]
  }
}
```



**note**: `content` is ExT-dependent, shown above is the EqEx one. User not authorized as teacher or admin will receive answers. \
**note**: `seed` property is optional. It may be given if user is authorized as teacher or admin. For students it will be taken from database.

# Subject

## `POST /api/subject/create`

| Method | URL                   | Description        | Special status codes |
| ------ | --------------------- | ------------------ | -------------------- |
| POST   | `/api/subject/create` | create new subject | 403                  |

**Request**:

```json
{
  "id": "mechanika",
  "users": ["e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"]
}
```

**Response**:

```json

```

**note**: `subject` id is its name, it has to be unique. \
**note**: `groups` property tells who has access to subject. If is set to `"public"`, everyone can access it. \
**note**: If you want only individual users to access the subject, set groups to `[]`, and use ` /api/subject/permit`.

---

## `GET /api/subject/info`

| Method | URL                 | Description                  | Special status codes |
| ------ | ------------------- | ---------------------------- | -------------------- |
| GET    | `/api/subject/info` | get list of authorized users | 403, 404             |

**Request**:

```json
{
  "id": "mechanika"
}
```

**Response**:

```json
[
  {
    "id": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "name": "User"
  }
]
```

---

## `POST /api/subject/permit`

| Method | URL                   | Description                     | Special status codes |
| ------ | --------------------- | ------------------------------- | -------------------- |
| POST   | `/api/subject/permit` | change list of authorized users | 403, 404             |

**Request**:

```json
{
  "id": "mechanika",
  "users": [
    {
      "id": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      "name": "User"
    }
  ]
}
```

**Response**:

```json

```

# Auth

## `POST /api/auth/register`

| Method | URL                  | Description         | Special status codes                                 |
| ------ | -------------------- | ------------------- | ---------------------------------------------------- |
| POST   | `/api/auth/register` | register a new user | 403 (wrong invitation), 409 (account already exists) |

**Request**:

```json
{
  "login": "user@example.com",
  "name": "User",
  "hashed_password": "r02H/fnQ3M3Xfjqsr3dg8mY78lBDXWoiR0O0JcXW8VM=",
  "number": 11,
  "invitation": "QwErTy58"
}
```

**Response**:

```json

```

**note**: The generation of `hashed_password` is described [here](https://github.com/Pikne-Programy/pikne-zadania/issues/22#issuecomment-789536400). \
**note**: `number` is a number or `null` when it's not provided. \
**note**: `login` is an email address (the hard-coded users like `root` cannot be registered). \
**note**: The registration doesn't authenticate, there should be a `POST /api/login` request afterwards.

---

## `POST /api/auth/login`

| Method | URL               | Description  | Special status codes |
| ------ | ----------------- | ------------ | -------------------- |
| POST   | `/api/auth/login` | authenticate | -                    |

**Request**:

```json
{
  "login": "user@example.com",
  "hashed_password": "r02H/fnQ3M3Xfjqsr3dg8mY78lBDXWoiR0O0JcXW8VM="
}
```

**Response**:

```json

```

**note**: The generation of `hashed_password` is described [here](https://github.com/Pikne-Programy/pikne-zadania/issues/22#issuecomment-789536400).

---

## `POST /api/auth/logout`

| Method | URL                | Description    | Special status codes |
| ------ | ------------------ | -------------- | -------------------- |
| POST   | `/api/auth/logout` | unauthenticate | -                    |

**Request**:

```json

```

**Response**:

```json

```

# User

## `GET /api/user/current`

| Method | URL                 | Description                                 | Special status codes |
| ------ | ------------------- | ------------------------------------------- | -------------------- |
| GET    | `/api/user/current` | get info about currently authenticated user | -                    |

**Request**:

```json

```

**Response**:

```json
{
  "name": "User",
  "number": 11,
  "team": 1
}
```

## `DELETE /api/user/delete`

| Method | URL                | Description       | Special status codes |
| ------ | ------------------ | ----------------- | -------------------- |
| DELETE | `/api/user/delete` | unregister a user | 403, 404             |

**Request**:

```json
{
  "id": "1057a9604e04b274da5a4de0c8f4b4868d9b230989f8c8c6a28221143cc5a755"
}
```

**Response**:

```json

```

---

## `POST /api/user/update`

| Method | URL                | Description        | Special status codes |
| ------ | ------------------ | ------------------ | -------------------- |
| POST   | `/api/user/update` | update User's data | 403, 404             |

**Request**:

```json
{
  "id": "1057a9604e04b274da5a4de0c8f4b4868d9b230989f8c8c6a28221143cc5a755",
  "number": 34
}
```

**Response**:

```json

```

**note**: Possible paramters to change are `number` and `name`.

---

## `GET /api/user/info`

| Method | URL              | Description           | Special status codes |
| ------ | ---------------- | --------------------- | -------------------- |
| GET    | `/api/user/info` | get info about a user | 403, 404             |

**Request**:

```json
{
  "id": "1057a9604e04b274da5a4de0c8f4b4868d9b230989f8c8c6a28221143cc5a755"
}
```

**Response**:

```json
{
  "name": "User",
  "number": 11,
  "team": 1
}
```

# Team

## `POST /api/team/create`

| Method | URL                | Description     | Special status codes |
| ------ | ------------------ | --------------- | -------------------- |
| POST   | `/api/team/create` | create new team | 403                  |

**Request**:

```json
{
  "name": "2d"
}
```

**Response**:

```json
2
```

**note**: The response is an `id` of team.

---

## `DELETE /api/team/delete`

| Method | URL                | Description   | Special status codes |
| ------ | ------------------ | ------------- | -------------------- |
| DELETE | `/api/team/delete` | delete a team | 403, 404             |

**Request**:

```json
{
  "id": 3
}
```

**Response**:

```json

```

---

## `POST /api/team/update`

| Method | URL                | Description        | Special status codes                     |
| ------ | ------------------ | ------------------ | ---------------------------------------- |
| POST   | `/api/team/update` | change team's data | 403, 404, 409 (invitation code is taken) |

**Request**:

```json
{
  "id": 2,
  "invitation": "QwErTy58"
}
```

**Response**:

```json

```

**note**: Possible paramters to change are: `invitation`, `assignee`, `name`. \
**note**: `invitation` in request can also be `""` (in that case, it will be generated) or `null` (in that case, registration will be closed)

---

## `GET /api/team/list`

| Method | URL              | Description            | Special status codes |
| ------ | ---------------- | ---------------------- | -------------------- |
| GET    | `/api/team/list` | get list of your teams | 403                  |

**Request**:

```json

```

**Response**:

```json
[
  {
    "id": 1,
    "name": "Teachers",
    "assignee": "Smith",
    "invitation": "QwErTy58"
  },
  {
    "id": 2,
    "name": "2d",
    "assignee": "Williams",
    "invitation": null
  },
  {
    "id": 3,
    "name": "3d",
    "assignee": "Williams",
    "invitation": null
  }
]
```

**note**: There is always hard-coded `admin` team with id `0`. \
**note**: The authenticated user from `admin` team will get all teams. \
**note**: The authenticated user not from `admin` team will not get the `assignee` property. \
**note**: The authenticated user not from `admin` or `teacher` team will not get the `invitation` property.

---

## `GET /api/team/info`

| Method | URL              | Description         | Special status codes |
| ------ | ---------------- | ------------------- | -------------------- |
| GET    | `/api/team/info` | get info about team | 403                  |

**Request**:

```json

```

**Response**:

```json
{
  "name": "2d",
  "assignee": "Williams",
  "invitation": "QwErTy58",
  "members": [
    {
      "id": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      "name": "User",
      "number": 11
    }
  ]
}
```

**note**: Member `id` property is a hashed email. \
**note**: When team has closed registration `invitation` is `null`. \
**note**: Students will not receive `invitation` code.

# Group

## `POST /api/group/create`

| Method | URL                 | Description        | Special status codes |
| ------ | ------------------- | ------------------ | -------------------- |
| POST   | `/api/group/create` | create a new group | 403                  |

**Request**:

```json
{
  "id": "fizyka2D"
}
```

**Response**:

```json

```

**note**: Group's name is its id. It can always be changed provided new id is unique.

---

## `DELETE /api/group/delete`

| Method | URL                 | Description    | Special status codes |
| ------ | ------------------- | -------------- | -------------------- |
| DELETE | `/api/group/delete` | delete a group | 403, 404             |

**Request**:

```json
{
  "id": "fizyka2D"
}
```

**Response**:

```json

```

---

## `POST /api/group/update`

| Method | URL                 | Description         | Special status codes                      |
| ------ | ------------------- | ------------------- | ----------------------------------------- |
| POST   | `/api/group/update` | change group's data | 403, 404 , 409 (invitation code is taken) |

**Request**:

```json
{
  "id": "fizyka2D",
  "invitation": "QwErTy58"
}
```

**Response**:

```json

```

**note**: Possible paramters to change are: `invitation` and `assignee`.

---

## `GET /api/group/list`

| Method | URL               | Description         | Special status codes |
| ------ | ----------------- | ------------------- | -------------------- |
| GET    | `/api/group/list` | get all your groups | -                    |

**Request**:

```json

```

**Response**:

```json
{
[
  {
    "id": "angielski2D",
    "assignee": "Smith",
    "invitation": "QwErTy58"
  },
  {
    "id": "fizyka2D",
    "assignee": "Williams",
    "invitation": "XzT87"
  },
  {
    "id": "matematyka2D",
    "assignee": "Williams",
    "invitation": null
  }
]
}
```

**note**: Only `root` will receive `assignee` property \
**note**: Students will not receive `invitation` code.

---

## `GET /api/group/info`

| Method | URL               | Description            | Special status codes |
| ------ | ----------------- | ---------------------- | -------------------- |
| GET    | `/api/group/info` | get info about a group | 403, 404             |

**Request**:

```json
{
  "id": "fizyka2D"
}
```

**Response**:

```json
{
  "id": "fizyka2D",
  "assignee": "Williams",
  "invitation": "QwErTy58",
  "members": [
    {
      "id": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      "name": "User",
      "number": 11
    }
  ],
  "exams": [
    { "id": 147, "name": "kinematyka 1" },
    { "id": 157, "name": "dynamika 2" }
  ]
}
```

**note**: When a group has closed registration `invitation` is `null`. \
**note**: Student will not receive `invitation` code. \
**note**: Number is from `user`'s team so collisions are possible. \
**note**: `exams` are tuples containing exam's `name` and `id`.

# Exam

## `POST /api/exam/create`

| Method | URL                | Description     | Special status codes |
| ------ | ------------------ | --------------- | -------------------- |
| POST   | `/api/exam/create` | create new exam | 403                  |

**Request**:

```json
{
  "name": "Sprawdzian dynamika",
  "start": 1620077373,
  "duration": 2700,
  "group": "fizyka2D"
}
```

**Response**:

```json
153
```

**note**: `start` time is given as seconds elapsed from 01.01.1970. \
**note**: Response is an `id` of the created exam.

---

## `DELETE /api/exam/delete`

| Method | URL                | Description    | Special status codes |
| ------ | ------------------ | -------------- | -------------------- |
| Delete | `/api/exam/delete` | delete an exam | 403, 404             |

**Request**:

```json
{
  "id": 153
}
```

**Response**:

```json

```

---

## `POST /api/exam/update`

| Method | URL                | Description    | Special status codes |
| ------ | ------------------ | -------------- | -------------------- |
| POST   | `/api/exam/update` | update an exam | 403, 404             |

**Request**:

```json
{
  "id": 12451,
  "duration": 3000
}
```

**Response**:

```json

```

**note**: Possible paramters to change are: `name`, `group`, `time`, `duration`.

---

## `POST /api/exam/exercise`

| Method | URL                  | Description   | Special status codes |
| ------ | -------------------- | ------------- | -------------------- |
| POST   | `/api/exam/exercise` | add exercises | 403, 404             |

**Request**:

```json
{
  "id": 153,
  "exercises": [{ "count": 1, "ex": ["fizyka/pociagi-dwa", "fizyka/czerpak"] }]
}
```

**Response**:

```json

```

---

## `GET /api/exam/info`

| Method | URL              | Description         | Special status codes |
| ------ | ---------------- | ------------------- | -------------------- |
| GET    | `/api/exam/info` | get info about exam | 403, 404             |

**Request**:

```json
{
  "id": 153
}
```

**Response**:

```json
{
  "status": "off",
  "start": 1620077373,
  "duration": 2700,
  "group": "fizyka2D",
  "pool": [
    {
      "count": 1,
      "ex": ["fizyka/pociagi-dwa", "fizyka/czerpak"],
      "points": 10
    }
  ]
}
```

**note**: Every exercise has `points` number of points.

---

## `GET /api/exam/user`

| Method | URL              | Description    | Special status codes |
| ------ | ---------------- | -------------- | -------------------- |
| GET    | `/api/exam/user` | get user stats | 403, 404             |

**Request**:

```json
{
  "id": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  "eid": 153
}
```

**Response**:

```json
{
  "score": 0.9,
  "points": 9,
  "grade": "bdb",
  "exercises": {
    "pociagi-dwa": 1,
    "czerpak": 0
  }
}
```

---

## `GET /api/exam/stats`

| Method | URL               | Description    | Special status codes |
| ------ | ----------------- | -------------- | -------------------- |
| GET    | `/api/exam/stats` | get exam stats | 403, 404             |

**Request**:

```json
{
  "id": 153
}
```

**Response**:

```json
{
  "exercises": [
    { "id": "fizyka/pociagi-dwa", "points": 10, "avg": 5 },
    { "id": "fizyka/czerpak", "points": 10, "avg": 0 }
  ],
  "users": [
    {
      "id": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      "solvings": [[5, 0.5], null],
      "points": 5,
      "percent": 0.5,
      "grade": "dst"
    }
  ]
}
```

---

**Comment by Nircek** [comment]
A lot of work was done.
![work](https://user-images.githubusercontent.com/26528678/129189061-9b5e07a2-b176-4a1b-bb59-abaaad10f46b.png)

**Comment by Nircek** [comment]
We tended to use the undocumented 201 HTTP code without any `Location` tag. We will use only a 200 HTTP status code in the v0.3 prototype.

**Comment by Nircek** [comment]
Okay, so I have rewritten all the Wiki into AsciiDoc. It took me like 8 hours. Was it worth it? We will see.

I will disable GitHub's Wiki soon due to its deprecation.

These are old revisions for reference:

# Old API v0.3 revisions
- [Revision 3 [.adoc]](https://github.com/Pikne-Programy/pikne-zadania/blob/462081bae99d28c918efb4f3360fdc588edaa218/API.adoc) (462081bae99d28c918efb4f3360fdc588edaa218)
- [Revision 2](https://github.com/Pikne-Programy/pikne-zadania/blob/882dfe08d8b017ed6caddbcc5f704300606eb0c0/API.md) (882dfe08d8b017ed6caddbcc5f704300606eb0c0)
- [Revision 1.1 [corrected]](https://github.com/Pikne-Programy/pikne-zadania/blob/0fb05588d4742a03516d5e28fb76aed02c301c32/API.md) (0fb05588d4742a03516d5e28fb76aed02c301c32)
- [Revision 1](https://github.com/Pikne-Programy/pikne-zadania/blob/e19a30592bd0744b52bc66d88c224c6282e66ecd/API.md) (e19a30592bd0744b52bc66d88c224c6282e66ecd)
- [Revision 0](https://github.com/Pikne-Programy/pikne-zadania/blob/8efcb216f0880d3bbeb1e844999e2eebd63b4195/API.md) (8efcb216f0880d3bbeb1e844999e2eebd63b4195)

**Comment by Nircek** [comment]
![The Wiki was disabled.](https://user-images.githubusercontent.com/26528678/132685840-68e5abd7-acf8-461d-9882-28c222e1a94d.png)
