### ISSUE TITLE
Permissions to edit exercises [subject assignees]

### ISSUE THREAD

**Issue by Nircek** [Pikne-Programy/pikne-zadania#36]
In the new API (#34), we want to add a possibility to get and update the raw content of exercises. Although, there should be some limitations about that, so we need to add permissions.

**Comment by Nircek** [comment]
The permissions should be stored in database.

**Comment by Nircek** [comment]
The API (#34) has `assignees` properties, so it fully supports permissions now. The `assignees` is a list of ids of users that can manage a subject. Therefore they can edit exercises in it as well. The question arises: can the Student specified in the list change exercises' content? I think the answer is yes because why not. One User had to assign them. 

 @miloszwasacz, would you support editing exercises by the Student?

> The permissions should be stored in database.

@Marwyk2003, you take care of it, ok?

**Comment by miloszwasacz** [comment]
If an assigned Student is able to modify exercises, then should they be able to modify subjects hierarchy as well?

**Comment by Nircek** [comment]
I think so. It comes to my mind that we could make partial permissions somehow. Although it shouldn't bother us in this prototype, so let's forget about it.

**Comment by Nircek** [comment]
Not tested, but done. Closing...
