### ISSUE TITLE
ExercisesController connected to the oak framework

### ISSUE THREAD

**Issue by Nircek** [Pikne-Programy/pikne-zadania#7]
depends on #1 and #4

**Comment by Nircek** [comment]
So it's `ExercisesController` connected to the oak framework...

**Comment by MichalTheProgrammer** [comment]
We have to decide what do we need in the `Exercise interface`.
For sure we do need an identification like **"name"**.
We also need to decide whether we want to keep parsed content or only path to it. The same issue is with a solution in EqEx. Well at this point I have totally forgotten about **"type"** like EqEx etc. Below I'm going to paste a sample code with `Exercise interface`. 

interface Exercise
{
    type : string; // EqEx etc. 
    name : string; //Pociągi 2
    source : string; // path to .txt file ../pociągi-dwa.txt
    content : string; // pociągi-dwa.txt`]
    solution : string; // ["t=300/(v_a+v_b)", " x=t*v_a"]
    points ?: number; // optionally assign points to this exercise
} 

Obviously, this is just unacceptable because I gathered all data we could need. However, it is not necessary to use all of it. So @Nircek @Marwyk2003 try to choose those which are essential.

**Comment by Nircek** [comment]
First of all, @Marwyk2003 wants to do it by Reverse Polish Notation so in my opinion a storing how to calculate solutions in `t=300/(v_a+v_b)` is just resource-consuming. We should somehow keep it in RPN, but I have no idea how.

@Marwyk2003 maybe instead of just one array, make it more OOP and create an object like `RPN` which wants arguments (like `v_a` and `v_b`) and returns a calculated value? We should test it in practice.

And the `Exercise interface` should be more general, so id, name, description, type and type-dependent... parameters should be all. There will be no points in public ExDB, and we will make private ExDB on top of the public one, and then we will add points.

**Comment by Nircek** [comment]
And the Exercise itself should have a function to generate what to send users when they want to get the content of Ex and another one to check a list of users' solutions.

**Comment by MichalTheProgrammer** [comment]
I think we should talk about it in the nearest future. But I was thinking about the interface. The function You mentioned (function to generate what to send users) in my opinion can be in exercise.ts (which would be in controllers folder) and the interface would be in types.ts (I think it is a good idea if we want to add users in the future).  And I think that points are also worth considering especially in EqEx where there might be more than sub-exercises (e.g. find velocity and time). And typescript guarantees us optional parameters.

**Comment by Nircek** [comment]
Okay, I don't see your view in https://github.com/Pikne-Programy/pikne-zadania/issues/7#issuecomment-757955110, but we met yesterday which ended with d0711767bedf6fabd2f3e6d51dfde2813e936a89.

@Marwyk2003 is going now to #4 and his [Marwyk2003/EquationParser](https://github.com/Marwyk2003/EquationParser). Thus I can unassign him.

**Comment by Nircek** [comment]
@MichalTheProgrammer see 3e9eeb642c46472afbe3dadb8f549bb12f0a906c. Please fill it with working code.

**Comment by Nircek** [comment]
The controller should send minified JSON because currently, it's sending a lot of useless spaces. I know they are in the Wiki, but they're there due to clarity.
We've changed the API (see https://github.com/Pikne-Programy/pikne-zadania/issues/1#issuecomment-766158306) and the way of storing exercises (see https://github.com/Pikne-Programy/pikne-zadania/issues/17#issuecomment-766157678), so there should be fixes.

**Comment by Nircek** [comment]
Okay, I can see the new completed API support.

> The controller should send minified JSON because currently, it's sending a lot of useless spaces. I know they are in the Wiki, but they're there due to clarity.

@MichalTheProgrammer what about a minified JSON, have you thought about it?

**Comment by MichalTheProgrammer** [comment]
Not yet, however, I'll try to do something in one week time.

**Comment by Nircek** [comment]
It's not necessary for now so we can skip it in the first prototype. But I'd like to keep open this issue due to minification lack.

**Comment by Nircek** [comment]
Or the better way is to combine the API response minification with the frontend minification (#13). It has nothing to do with it, but we can have the issue closed.
